# Generated by Django 5.0.2 on 2024-05-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='body',
            new_name='message',
        ),
    ]
