# Generated by Django 5.0.2 on 2024-02-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
