# Generated by Django 5.0.2 on 2024-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_associate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='name',
        ),
        migrations.AddField(
            model_name='associate',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
