# Generated by Django 5.0.2 on 2024-02-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_associate_name_associate_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='age',
        ),
    ]
