# Generated by Django 5.0.2 on 2024-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_associate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
