# Generated by Django 5.0.2 on 2024-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_associate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='associate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
