# Generated by Django 5.0.2 on 2024-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_associate_user'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='associate',
        #     name='reg_id',
        #     field=models.CharField(max_length=8, unique=True),
        # ),
    ]
