# Generated by Django 5.0.2 on 2024-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_associate_reg_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='associate',
        #     name='reg_id',
        # ),
    ]
