# Generated by Django 5.0.2 on 2024-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_associate_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
