# Generated by Django 5.0.2 on 2024-04-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_is_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
