# Generated by Django 5.0.2 on 2024-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('temp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
