# Generated by Django 5.0.2 on 2024-03-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_associate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.DateField()),
                ('is_mrng', models.BooleanField(default=False)),
                ('is_noon', models.BooleanField(default=False)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.associate')),
            ],
        ),
    ]
