# Generated by Django 5.0.2 on 2024-03-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='delete',
            new_name='date',
        ),
    ]
