# Generated by Django 5.0.2 on 2024-03-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_delete_available_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='is_mrng',
            new_name='is_morning',
        ),
    ]
