# Generated by Django 5.0.2 on 2024-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='date',
            field=models.DateField(),
        ),
    ]
