# Generated by Django 5.0.2 on 2024-04-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='HC9999', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='confirmed', max_length=100, null=True),
        ),
    ]
