# Generated by Django 5.0.2 on 2024-04-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_booking_id_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='HC9999', max_length=10, unique=True),
        ),
    ]
