# Generated by Django 5.0.2 on 2024-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('booked', 'booked')], default='active', max_length=100),
        ),
    ]
