# Generated by Django 5.0.2 on 2024-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_available_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, default='kochi', max_length=200, null=True),
        ),
    ]
