# Generated by Django 5.0.2 on 2024-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('booked', 'booked'), ('asociate_blocked', 'asociate_blocked')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('cancelled_by_admin', 'cancelled_by_admin')], default='confirmed', max_length=100, null=True),
        ),
    ]
