# Generated by Django 5.0.2 on 2024-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('booked', 'booked'), ('completed', 'completed'), ('asociate_blocked and cancelled', 'asociate_blocked and cancelled')], default='active', max_length=100),
        ),
    ]
